### ISSUE TITLE
Crafting manager GUI is not accessible

### ISSUE THREAD

**Issue by rsg888** [KorewaLidesu/TestBridge#22]
**Describe the bug**
When you click on a crafting manager, nothing happens, GUI doesn't open. 

**To Reproduce**
1. Click on crafting manager with LP Pipe Manager(or any other wrench)
2. See that nothing happens

**Expected behavior**
Crafting Manager GUI opens on click

**Mod versions:**
 - Forge Version: 14.23.5.2860
 - MixinBooter: 8.6 - 9.1
 - LogisticsPipes: 0.10.4.46 - 0.10.4.49
 - ModularUI: 2.1.0 - 2.2.0
 - TestBridge: 0.4.0

**Additional context**
Immediately after right-clicking crafting manager the following is logged:

```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: logisticspipes.utils.gui.DummyContainer cannot be cast to net.jp.hellparadise.testbridge.helpers.interfaces.lp.ExtendedDummyContainer
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassCastException: logisticspipes.utils.gui.DummyContainer cannot be cast to net.jp.hellparadise.testbridge.helpers.interfaces.lp.ExtendedDummyContainer
    at net.jp.hellparadise.testbridge.network.guis.pipe.CMGuiProvider.getContainer(CMGuiProvider.java:79)
    at net.jp.hellparadise.testbridge.network.guis.pipe.CMGuiProvider.getContainer(CMGuiProvider.java:24)
    at logisticspipes.network.NewGuiHandler.openGui(NewGuiHandler.java:80)
    at logisticspipes.network.abstractguis.GuiProvider.open(GuiProvider.java:38)
    at logisticspipes.pipes.basic.CoreRoutedPipe.blockActivated(CoreRoutedPipe.java:916)
    at logisticspipes.pipes.basic.LogisticsBlockGenericPipe.onBlockActivated(LogisticsBlockGenericPipe.java:766)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

No Mixin Metadata is found in the Stacktrace.

```
There is also this warning during loading:

```
[09:21:08] [Client thread/WARN] [mixin]: Mixin apply for mod unknown-owner failed mixin.testbridge.logisticspipes.json:inventories.TB_DummyContainer from mod unknown-owner -> logisticspipes.utils.gui.DummyContainer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method addSlotToContainer in mixin.testbridge.logisticspipes.json:inventories.TB_DummyContainer from mod unknown-owner was not located in the target class logisticspipes.utils.gui.DummyContainer. Using refmap mixin.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method addSlotToContainer in mixin.testbridge.logisticspipes.json:inventories.TB_DummyContainer from mod unknown-owner was not located in the target class logisticspipes.utils.gui.DummyContainer. Using refmap mixin.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1290) ~[!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377) [!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) [!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) [!mixinbooter-9.1(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:71) [!mixinbooter-9.1(1).jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_412]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_412]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_412]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) [?:1.8.0_412]
	at java.lang.Class.getConstructors(Class.java:1651) [?:1.8.0_412]
	at logisticspipes.network.NewGuiHandler.loadGuiProviders(NewGuiHandler.java:65) [NewGuiHandler.class:0.10.4.46]
	at logisticspipes.network.NewGuiHandler.initialize(NewGuiHandler.java:47) [NewGuiHandler.class:0.10.4.46]
	at logisticspipes.LogisticsPipes.preInit(LogisticsPipes.java:436) [LogisticsPipes.class:0.10.4.46]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandlerMixin.java:252) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(MinecraftMixin.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(MinecraftMixin.java:5101) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```

**Comment by KorewaLidesu** [comment]
Thanks for the report. I will take a look at it once I free.
